pyinstaller --onefile ./src/publish/xhs_article.py
pyinstaller --onefile ./src/publish/xhs_video.py
pyinstaller --onefile ./src/publish/dy_video.py
pyinstaller --onefile ./src/publish/wx_video.py
pyinstaller --onefile ./src/generate/article_generate.py
pyinstaller --onefile ./src/generate/video_generate.py
pyinstaller --onefile ./src/clear/article_clear.py
pyinstaller --onefile ./src/clear/video_clear.py
pyinstaller --onefile ./src/entry.py